services:
  rsshub:
    image: diygod/rsshub:chromium-bundled@sha256:e75051d2b199368755cd6e595c332ac01b7af3c2433569b7e29cccde71a33623
    hostname: rsshub
    container_name: rsshub__rsshub

    restart: unless-stopped

    environment:
      TWITTER_AUTH_TOKEN: ${TWITTER_AUTH_TOKEN}

    deploy:
      resources:
        limits:
          memory: 1024m

    networks:
      - default

  nginx:
    image: nginx:1.28.0@sha256:eaa7e36decc3421fc04478c586dfea0d931cebe47d5bc0b15d758a32ba51126f
    hostname: nginx
    container_name: rsshub__nginx

    restart: unless-stopped

    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true

      - type: bind
        source: ./.htpasswd
        target: /etc/htpasswd
        read_only: true

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      default:

  cloudflared:
    image: cloudflare/cloudflared:2025.5.0@sha256:f9d5c5b94cd7337c0c939a6dbf5537db34030828c243fca6b589fd85ab25d43b
    hostname: cloudflared
    container_name: rsshub__cloudflared

    restart: unless-stopped

    environment:
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      default:

networks:
  default:
    name: rsshub__default
