services:
  rsshub:
    image: diygod/rsshub:chromium-bundled@sha256:8d44cd27fc21dafb1b4b26218559f9932f0d6da3b2e4d09d367c44bb5a5454fe
    hostname: rsshub
    container_name: rsshub__rsshub

    restart: unless-stopped

    environment:
      TWITTER_AUTH_TOKEN: ${TWITTER_AUTH_TOKEN}

    deploy:
      resources:
        limits:
          memory: 1024m

    networks:
      - default

  nginx:
    image: nginx:1.29.0@sha256:93230cd54060f497430c7a120e2347894846a81b6a5dd2110f7362c5423b4abc
    hostname: nginx
    container_name: rsshub__nginx

    restart: unless-stopped

    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true

      - type: bind
        source: ./.htpasswd
        target: /etc/htpasswd
        read_only: true

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      default:

  cloudflared:
    image: cloudflare/cloudflared:2025.7.0@sha256:803b17adb5326a38ce397b9c9f374289ad290ee5526d204b5879a1423b6f5c3e
    hostname: cloudflared
    container_name: rsshub__cloudflared

    restart: unless-stopped

    environment:
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      default:

networks:
  default:
    name: rsshub__default
