services:
  rsshub:
    image: diygod/rsshub:chromium-bundled@sha256:ea89f059dbddbc33998756a85c403b6aa637666b053b51b53e07d93006686335
    hostname: rsshub
    container_name: rsshub__rsshub

    restart: unless-stopped

    environment:
      TWITTER_AUTH_TOKEN: ${TWITTER_AUTH_TOKEN}

    deploy:
      resources:
        limits:
          memory: 1024m

    networks:
      - default

  nginx:
    image: nginx:1.31.0@sha256:06aa3d7be10bc6307990c81bdca075793132e9163391abc370c015e344e23128
    hostname: nginx
    container_name: rsshub__nginx

    restart: unless-stopped

    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true

      - type: bind
        source: ./.htpasswd
        target: /etc/htpasswd
        read_only: true

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      default:

  cloudflared:
    image: cloudflare/cloudflared:2026.3.0@sha256:6b599ca3e974349ead3286d178da61d291961182ec3fe9c505e1dd02c8ac31b0
    hostname: cloudflared
    container_name: rsshub__cloudflared

    restart: unless-stopped

    environment:
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      default:

networks:
  default:
    name: rsshub__default
